/**
 * Details of the job that ran the operation
 * (only present when operation was run from a job)
 */
export interface JobInfo {
  jobId: string;
  jobName?: string;
  runId?: string;
  jobOwnerId?: string;
  triggerType?: string;
}

/**
 * Details of the notebook from which the operation was run
 * (only present when operation was run from a notebook)
 */
export interface NotebookInfo {
  notebookId: string;
  notebookPath?: string;
}

/**
 * Parameters of the operation (varies by operation type)
 * Common parameters include predicates, mode, partitionBy, etc.
 */
export interface OperationParameters {
  mode?: string;                    // e.g., "Append", "Overwrite", "ErrorIfExists"
  partitionBy?: string;             // JSON string of partition columns, e.g., "[\"date\"]"
  predicate?: string;               // For DELETE/UPDATE operations
  matchedPredicates?: string;       // For MERGE operations
  notMatchedPredicates?: string;    // For MERGE operations
  notMatchedBySourcePredicates?: string;
  [key: string]: unknown;           // Allow additional parameters
}

/**
 * Metrics of the operation - keys vary by operation type
 *
 * Common metrics by operation:
 * - WRITE/CREATE TABLE AS SELECT: numFiles, numOutputBytes, numOutputRows
 * - STREAMING UPDATE: numAddedFiles, numRemovedFiles, numOutputRows
 * - DELETE: numDeletedRows, numRemovedFiles, numAddedFiles, numCopiedRows
 * - UPDATE: numUpdatedRows, numRemovedFiles, numAddedFiles, numCopiedRows
 * - MERGE: numTargetRowsInserted, numTargetRowsUpdated, numTargetRowsDeleted, etc.
 * - OPTIMIZE: numAddedFiles, numRemovedFiles, numAddedBytes, numRemovedBytes
 */
export interface OperationMetrics {
  // Write operations
  numFiles?: string;
  numOutputBytes?: string;
  numOutputRows?: string;

  // File operations (common across many operations)
  numAddedFiles?: string;
  numRemovedFiles?: string;
  numAddedBytes?: string;
  numRemovedBytes?: string;

  // Row operations
  numTotalRows?: string;
  numCopiedRows?: string;
  numDeletedRows?: string;
  numUpdatedRows?: string;

  // Merge-specific metrics
  numTargetRowsInserted?: string;
  numTargetRowsUpdated?: string;
  numTargetRowsDeleted?: string;
  numTargetRowsCopied?: string;
  numSourceRows?: string;
  numTargetFilesAdded?: string;
  numTargetFilesRemoved?: string;

  // Optimize/compaction metrics
  numBatches?: string;
  totalConsideredFiles?: string;
  totalFilesSkipped?: string;
  preserveInsertionOrder?: string;

  // Restore metrics
  numRestoredFiles?: string;
  removedFilesSize?: string;
  restoredFilesSize?: string;

  // Catch-all for any other metrics
  [key: string]: string | undefined;
}

/**
 * Known Delta Lake operations
 */
export type DeltaOperation =
  | 'WRITE'
  | 'CREATE TABLE'
  | 'CREATE TABLE AS SELECT'
  | 'REPLACE TABLE'
  | 'REPLACE TABLE AS SELECT'
  | 'COPY INTO'
  | 'STREAMING UPDATE'
  | 'DELETE'
  | 'UPDATE'
  | 'MERGE'
  | 'OPTIMIZE'
  | 'VACUUM START'
  | 'VACUUM END'
  | 'RESTORE'
  | 'CLONE'
  | 'SET TBLPROPERTIES'
  | 'UNSET TBLPROPERTIES'
  | 'ADD CONSTRAINT'
  | 'DROP CONSTRAINT'
  | 'CHANGE COLUMN'
  | 'ADD COLUMNS'
  | 'DROP COLUMNS'
  | 'RENAME COLUMN'
  | 'CONVERT'
  | 'TRUNCATE'
  | string;  // Allow other operations not listed

/**
 * Isolation levels used for Delta operations
 */
export type IsolationLevel =
  | 'WriteSerializable'
  | 'Serializable'
  | 'SnapshotIsolation'
  | string;

/**
 * Complete interface for a single table history record
 * Based on: https://docs.databricks.com/aws/en/delta/history
 */
export interface TableHistoryRecord {
  /** Table version generated by the operation */
  version: number;

  /** When this version was committed (ISO 8601 timestamp string) */
  timestamp: string;

  /** ID of the user that ran the operation */
  userId: string | null;

  /** Name of the user that ran the operation */
  userName: string | null;

  /** Name of the operation (e.g., WRITE, DELETE, MERGE, UPDATE, OPTIMIZE) */
  operation: DeltaOperation;

  /** Parameters of the operation (e.g., predicates, mode, partitionBy) */
  operationParameters: OperationParameters;

  /** Details of the job that ran the operation (null if not run from a job) */
  job: JobInfo | null;

  /** Details of the notebook from which the operation was run (null if not from notebook) */
  notebook: NotebookInfo | null;

  /** ID of the cluster on which the operation ran */
  clusterId: string | null;

  /** Version of the table that was read to perform the write operation */
  readVersion: number | null;

  /** Isolation level used for this operation */
  isolationLevel: IsolationLevel | null;

  /** Whether this operation appended data (blind append = no read dependencies) */
  isBlindAppend: boolean | null;

  /** Metrics of the operation (e.g., number of rows and files modified) */
  operationMetrics: OperationMetrics | null;

  /** User-defined commit metadata if it was specified */
  userMetadata: string | null;
}

/**
 * Array of table history records (returned from DESCRIBE HISTORY)
 */
export type TableHistory = TableHistoryRecord[];
